/**
 * Use Case definitions — mirrors reference repo lib/use-cases.ts.
 * 15 use cases across commercial + disaster categories, capability levels
 * traditional → mldl → cognitive → agentic.
 */
import type { UseCase } from './types'

export const USE_CASES: UseCase[] = [
  // ═══ Commercial — Traditional (Level 1) ═══
  {
    id: 'intrusion',
    name: 'Intrusión en Zona Restringida',
    nameEn: 'Restricted Zone Intrusion',
    category: 'commercial',
    level: 'traditional',
    description: 'Detecta cuando una persona o vehículo entra en un ROI definido. Regla determinista — sin ML.',
    detectionClasses: ['person', 'car', 'truck'],
    ruleType: 'roi_breach',
    params: { threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email'],
    icon: 'shield',
    tier: 2,
    signal: 'ROI breach en zona de carga',
    value: 'Disuasión + evidencia inmediata',
  },
  {
    id: 'after_hours',
    name: 'Intrusión Vehicular Fuera de Horario',
    nameEn: 'After-Hours Vehicle Intrusion',
    category: 'commercial',
    level: 'traditional',
    description: 'Cualquier vehículo detectado después de horario de atención → Tier 2.',
    detectionClasses: ['car', 'truck', 'bus', 'motorcycle'],
    ruleType: 'time_gate',
    params: { timeGate: { after: '20:00', before: '06:00' }, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate'],
    icon: 'moon',
    tier: 2,
    signal: 'Vehículo 02:14 — fuera de horario',
    value: 'Reducción de robos nocturnos',
  },
  // ═══ Commercial — ML/DL (Level 2) ═══
  {
    id: 'crowd_surge',
    name: 'Avalancha de Multitud',
    nameEn: 'Crowd Surge Detection',
    category: 'commercial',
    level: 'mldl',
    description: 'z-score del conteo de personas vs línea base de 2 min. z>2.5 sostenido → Tier 2.',
    detectionClasses: ['person'],
    ruleType: 'density_anomaly',
    params: { threshold: 2.5, sustainTicks: 3 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email'],
    icon: 'users',
    tier: 2,
    signal: 'z=3.1 personas · estación norte',
    value: 'Prevención de avalanchas / pánico',
  },
  {
    id: 'parking',
    name: 'Estacionamiento — Ocupación',
    nameEn: 'Parking Occupancy',
    category: 'commercial',
    level: 'mldl',
    description: 'Cuenta vehículos en ROI. Reporta ocupación, no mapea espacios individuales.',
    detectionClasses: ['car', 'truck'],
    ruleType: 'count_threshold',
    params: { threshold: 0 },
    actions: ['log_tick'],
    icon: 'car',
    tier: 0,
    signal: '14 / 20 plazas ocupadas',
    value: 'Operación de parqueadero',
  },
  {
    id: 'queue_anomaly',
    name: 'Anomalía de Cola en Cajeros',
    nameEn: 'ATM Queue Anomaly',
    category: 'commercial',
    level: 'mldl',
    description: 'Detecta colas largas en zona de cajeros. z-score del conteo > 2 → Tier 1.',
    detectionClasses: ['person'],
    ruleType: 'density_anomaly',
    params: { threshold: 2.0, sustainTicks: 2 },
    actions: ['badge', 'log_hit'],
    icon: 'list',
    tier: 1,
    signal: 'Cola >12 personas · cajero 3',
    value: 'Experiencia de cliente / fraude',
  },
  {
    id: 'abandoned_object',
    name: 'Objeto Abandonado',
    nameEn: 'Abandoned Object',
    category: 'commercial',
    level: 'mldl',
    description: 'Objeto (mochila/maleta) detectado 5 ciclos sin persona cercana → Tier 2.',
    detectionClasses: ['backpack', 'suitcase', 'handbag'],
    ruleType: 'sustain_verify',
    params: { sustainTicks: 5, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email'],
    icon: 'package',
    tier: 2,
    signal: 'Mochila 7.5s sin dueño · hall',
    value: 'Seguridad antiterrorista',
  },
  // ═══ Commercial — Cognitive (Level 3) ═══
  {
    id: 'loitering',
    name: 'Merodeo Sospechoso',
    nameEn: 'Suspicious Loitering',
    category: 'commercial',
    level: 'cognitive',
    description: 'Persona >90s en ROI pequeño. VLM describe la actividad para filtrar falsos positivos.',
    detectionClasses: ['person'],
    ruleType: 'sustain_verify',
    params: { sustainTicks: 12, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email'],
    icon: 'eye',
    tier: 2,
    signal: 'Sujeto 2:14 merodeando · entrada',
    value: 'Reducción de merodeo / cascadado',
  },
  {
    id: 'slip_fall',
    name: 'Caída de Cliente',
    nameEn: 'Customer Slip & Fall',
    category: 'commercial',
    level: 'cognitive',
    description: 'Pose de persona → caída sostenida. VLM confirma y describe para reporte de seguro.',
    detectionClasses: ['person'],
    ruleType: 'sustain_verify',
    params: { sustainTicks: 3, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'generate_report'],
    icon: 'activity',
    tier: 2,
    signal: 'Caída detectada · pasillo 4',
    value: 'Seguridad del cliente + liability',
  },
  // ═══ Commercial — Agentic (Level 4) ═══
  {
    id: 'shoplifting',
    name: 'Hurto en Tienda',
    nameEn: 'Shoplifting',
    category: 'commercial',
    level: 'agentic',
    description: 'VLM observa ocultamiento de producto + salida sin pago. Juez LLM + escalate autónomo.',
    detectionClasses: ['person', 'backpack', 'handbag'],
    ruleType: 'sustain_verify',
    params: { sustainTicks: 4, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate', 'generate_report'],
    icon: 'shopping-bag',
    tier: 3,
    signal: 'Ocultamiento producto · sector 7',
    value: 'Pérdidas reducidas + evidencia legal',
  },
  // ═══ Disaster — INDECI / SINPAD compatible ═══
  {
    id: 'fire_smoke',
    name: 'Conato de Incendio',
    nameEn: 'Fire & Smoke Detection',
    category: 'disaster',
    level: 'mldl',
    description: 'Modelo especializado de fuego/humo. Dispara reporte INDECI automáticamente.',
    detectionClasses: ['fire', 'smoke'],
    ruleType: 'sustain_verify',
    params: { sustainTicks: 2, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate', 'generate_report'],
    indeciReport: true,
    icon: 'flame',
    tier: 3,
    signal: 'Humo detectado · almacén central',
    value: 'Respuesta INDECI < 60s',
  },
  {
    id: 'flood_watch',
    name: 'Vigilancia de Inundación',
    nameEn: 'Flood Watch',
    category: 'disaster',
    level: 'mldl',
    description: 'Cambio de nivel de agua en ROI ribereña. Sostenido 30s → Tier 3 + INDECI.',
    detectionClasses: ['flood', 'water'],
    ruleType: 'frame_diff',
    params: { threshold: 0.18, sustainTicks: 6 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate', 'generate_report'],
    indeciReport: true,
    icon: 'waves',
    tier: 3,
    signal: 'Nivel río Rímac +0.4m · 30s',
    value: 'Alerta SINPAD temprana',
  },
  {
    id: 'landslide',
    name: 'Movimiento de Tierra',
    nameEn: 'Landslide Detection',
    category: 'disaster',
    level: 'cognitive',
    description: 'Frame-diff + VLM confirma deslizamiento en ladera. Reporte georreferenciado.',
    detectionClasses: ['rock', 'debris', 'mud'],
    ruleType: 'frame_diff',
    params: { threshold: 0.25, sustainTicks: 3 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate', 'generate_report'],
    indeciReport: true,
    icon: 'mountain',
    tier: 3,
    signal: 'Deslizamiento · ladera Chosica',
    value: 'Evacuación preventiva',
  },
  {
    id: 'structural',
    name: 'Daño Estructural',
    nameEn: 'Structural Damage',
    category: 'disaster',
    level: 'cognitive',
    description: 'Post-sismo: VLM巡检 grietas / inclinación. Sostenido → Tier 3 + ingeniero.',
    detectionClasses: ['crack', 'debris'],
    ruleType: 'sustain_verify',
    params: { sustainTicks: 4, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate', 'generate_report'],
    indeciReport: true,
    icon: 'building',
    tier: 3,
    signal: 'Grieta 12cm · columna B3',
    value: 'Seguridad post-sismo',
  },
  {
    id: 'traffic_incident',
    name: 'Incidente Vial',
    nameEn: 'Traffic Incident',
    category: 'disaster',
    level: 'agentic',
    description: 'Vehículo detenido + peatón caído. Agente decide cierre de carril + reporte.',
    detectionClasses: ['car', 'truck', 'person'],
    ruleType: 'sustain_verify',
    params: { sustainTicks: 5, threshold: 1 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate', 'generate_report'],
    indeciReport: true,
    icon: 'traffic-cone',
    tier: 3,
    signal: 'Choque · Panamericana N km 42',
    value: 'Respuesta vial coordinada',
  },
  {
    id: 'crowd_density',
    name: 'Densidad de Multitud — Evento',
    nameEn: 'Event Crowd Density',
    category: 'commercial',
    level: 'agentic',
    description: 'z-score personas en evento. Agente gestiona escalonamiento de respuesta + juez LLM.',
    detectionClasses: ['person'],
    ruleType: 'density_anomaly',
    params: { threshold: 3.0, sustainTicks: 3 },
    actions: ['badge', 'snapshot', 'log_hit', 'send_email', 'escalate'],
    icon: 'user-check',
    tier: 3,
    signal: 'z=4.2 · estadio sur',
    value: 'Seguridad en eventos masivos',
  },
]

export const USE_CASE_BY_ID = Object.fromEntries(USE_CASES.map((u) => [u.id, u])) as Record<string, UseCase>

export const LEVEL_META: Record<string, { label: string; color: string }> = {
  traditional: { label: 'Traditional', color: '#64748b' },
  mldl: { label: 'ML / DL', color: '#0ea5e9' },
  cognitive: { label: 'Cognitive', color: '#8b5cf6' },
  agentic: { label: 'Agentic', color: '#ec4899' },
}
